### ISSUE TITLE
Failed at the ProgressiveWordPress@0.0.426 build script

### ISSUE THREAD

**Issue by tedmasterweb** [GoogleChrome/ProgressiveWordPress#1]
Please let me know if you need any other details about my machine or configuration. I have no idea how to solve this.

```
./ProgressiveWordPress-master/build.js:30
async function copyStatic() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
```

**Comment by surma** [comment]
Just an FYI: But it’s probably way too early to use this, very much in flux and WIP. I’ll put out actual articles and guidance once I am done.

Regarding this error: Looks like you are running an old version of Node that doesn’t have async functions yet. Node 8 (or maybe even Node 7?) should solve this.

**Comment by tedmasterweb** [comment]
Thanks. I updated to npm 5.0.2 and continued to have the error. Going to try getting node up to 7 or higher as suggested to see if that fixes things.

**Comment by tedmasterweb** [comment]
After updating node to 8 and installing babel-core and glob by specifying those modules explicitly I got the following results:

```
npm run build                 

> ProgressiveWordPress@0.0.437 build /Users/tedsr/Downloads/ProgressiveWordPress-master
> npm version --no-git-tag-version -f patch && mkdir -p dist; node build.js

npm WARN using --force I sure hope you know what you are doing.
v0.0.438
Done
(node:7636) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): Error: Couldn't find preset "babili" relative to directory "/Users/me/Downloads/ProgressiveWordPress-master"
(node:7636) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm happy to help debug this. I think this is a cool project. I just need a little encouragement.

**Comment by surma** [comment]
Hm, apparently I forgot to add `babili` to my dependencies. If you install that, it should work.

I’ll fix that on my end too :)

**Comment by tedmasterweb** [comment]
Cool. I got it up and running after installing babili.

**Comment by felipenmoura** [comment]
Hi.
Just to be sure...is this _babili preset_ the same one marked now as deprecated?
https://www.npmjs.com/package/babel-preset-babili
