### ISSUE TITLE
iOS Safari: content missing

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/ProgressiveWordPress#2]
1. Load https://pwp.dassur.ma/ in iOS Safari.
2. Tap on a link to e.g. a blog post.

Expected:

Content appears.

Actual:

Content does not appear. (Header and footer are visible, but not the "body".)

![img_1711](https://user-images.githubusercontent.com/51244/28519324-045202e0-7063-11e7-9544-49380cf7e80f.PNG)

**Comment by surma** [comment]
Fixed in a1bf2d1eef66720bed0cfd7bc59dda33531abcfb
